#!/usr/bin/env bash
# Switch the active board target between Raspberry Pi Pico and Pico W.
#
# What this script updates:
#   CMakeLists.txt  - PICO_BOARD value consumed by pico_sdk_init()
#   Sources/Board/RP2040/GPIO.swift - internalLedPin constant
#
# Usage:
#   Scripts/switch.sh pico    # target the original Raspberry Pi Pico
#   Scripts/switch.sh picow   # target the Raspberry Pi Pico W
#
# After switching, run Scripts/run.sh (or Scripts/run.sh --no-flash) to
# rebuild firmware for the new board.
#
# Note on Pico W LED: the on-board LED on the Pico W is wired to the CYW43
# wireless chip, not to a standard RP2040 GPIO pin. Driving it requires the
# CYW43 driver (pico_cyw43_arch). The virtual pin number 32 is the value the
# Pico SDK uses to identify CYW43_WL_GPIO_LED_PIN. Direct MMIO writes to GPIO
# 32 will NOT illuminate the LED; integrate the cyw43_arch library for full
# Pico W LED support.

set -euo pipefail

# Prints a standard progress message.
log() { printf "==> %s\n" "$*"; }
# Prints an error message and exits with failure.
fail() { printf "❌ %s\n" "$*"; exit 1; }

# Absolute path to the project root folder (one level above Scripts/).
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CMAKE_LISTS="${PROJECT_ROOT}/CMakeLists.txt"
GPIO_SWIFT="${PROJECT_ROOT}/Sources/Board/RP2040/GPIO.swift"

# ------------------------------------------------------------
# Section: usage
# ------------------------------------------------------------

print_usage() {
  cat <<'EOF'
Usage: Scripts/switch.sh <board>

Boards:
  pico   Raspberry Pi Pico  (LED on GPIO 25)
  picow  Raspberry Pi Pico W (LED on CYW43 virtual pin 32)

Options:
  -h, --help  Show this help text and exit.
EOF
}

# ------------------------------------------------------------
# Section: argument parsing
# ------------------------------------------------------------

BOARD=""

parse_args() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
      pico|picow)
        BOARD="$1"
        ;;
      -h|--help)
        print_usage
        exit 0
        ;;
      *)
        fail "Unknown argument: $1 (use --help)"
        ;;
    esac
    shift
  done

  [ -n "${BOARD}" ] || { print_usage; fail "A board name is required."; }
}

# ------------------------------------------------------------
# Section: update helpers
# ------------------------------------------------------------

# Update the PICO_BOARD value in CMakeLists.txt.
# The line being matched is generated by this script or the initial project
# template:  set(PICO_BOARD <value>)
update_cmake() {
  local board_name="$1"
  local cmake_board

  case "${board_name}" in
    pico)  cmake_board="pico" ;;
    picow) cmake_board="pico_w" ;;
  esac

  [ -f "${CMAKE_LISTS}" ] || fail "CMakeLists.txt not found at ${CMAKE_LISTS}"

  # Replace the first occurrence of  set(PICO_BOARD ...) with the new value.
  # We use sed in-place; BSD sed (macOS) requires an empty-string backup arg.
  if sed --version 2>/dev/null | grep -q GNU; then
    sed -i "s/set(PICO_BOARD [^)]*)/set(PICO_BOARD ${cmake_board})/" "${CMAKE_LISTS}"
  else
    sed -i '' "s/set(PICO_BOARD [^)]*)/set(PICO_BOARD ${cmake_board})/" "${CMAKE_LISTS}"
  fi

  log "CMakeLists.txt: PICO_BOARD set to ${cmake_board}"
}

# Update the internalLedPin constant in GPIO.swift.
# The line being matched is written by this script or added manually and has
# the form:  static let internalLedPin: UInt32 = <number>
update_gpio_swift() {
  local board_name="$1"
  local led_pin

  case "${board_name}" in
    pico)  led_pin=25 ;;
    # 32 is CYW43_WL_GPIO_LED_PIN as used by the Pico SDK. Direct GPIO MMIO
    # writes will not reach the LED; see the note at the top of this script.
    picow) led_pin=32 ;;
  esac

  [ -f "${GPIO_SWIFT}" ] || fail "GPIO.swift not found at ${GPIO_SWIFT}"

  if sed --version 2>/dev/null | grep -q GNU; then
    sed -i "s/static let internalLedPin: UInt32 = [0-9]*/static let internalLedPin: UInt32 = ${led_pin}/" \
      "${GPIO_SWIFT}"
  else
    sed -i '' "s/static let internalLedPin: UInt32 = [0-9]*/static let internalLedPin: UInt32 = ${led_pin}/" \
      "${GPIO_SWIFT}"
  fi

  log "GPIO.swift: internalLedPin set to ${led_pin}"
}

# ------------------------------------------------------------
# Section: main
# ------------------------------------------------------------

main() {
  parse_args "$@"
  update_cmake "${BOARD}"
  update_gpio_swift "${BOARD}"

  log "Board switched to: ${BOARD}"
  log "Rebuild firmware: Scripts/run.sh --no-flash"
}

main "$@"
